### ISSUE TITLE
[feature] Exchange across buffers

### ISSUE THREAD

**Issue by PythonNut** [Dewdrops/evil-exchange#7] opened 2016-04-01 18:15 UTC
This may be a somewhat unreasonable request, but here we go:

It would be really cool if we could exchange objects across buffers.

**Comment by Dewdrops** [comment] 2016-04-05 07:06
Thanks for your feedback.

Yes I think it's cool to operate across the buffer boundary. But may someone would like to have buffer local exchange position set? Currently none of them (buffer local or buffer across exchange) has been implemented, maybe we can add a user option for this?

I'm not sure what's the real user case (since I always exchange objects within the same buffer), what's your view on this?

@PythonNut

**Comment by PythonNut** [comment] 2016-04-05 15:25
I admit, exchanging across buffers won't probably be used as often as in-buffer. But here's a use case:

Suppose I'm testing several versions of a function:

**`factorial_defs.py`** (buffer)
```python
def factorial(n):
    "Iterate by recursion"
    if n == 0: return 1
    return n * factorial(n - 1)

def factorial(n):
    "Iterate normally"
    res = 1
    for factor in range(1, n + 1):
        res *= factor
    return res
```

**`factorial_test.py`** (file)
```python
def factorial(n):
    "Iterate by functional reduction"
    return reduce(lambda x, y: x * y, range(1, n + 1))

if __name__ == '__main__':
    for x in range(100000):
        print(factorial(x))
```

If I want to quickly test iteration by recursion, I can exchange the definitions of the function:

**`factorial_defs.py`** (buffer)
```python
def factorial(n):
    "Iterate by functional reduction"
    return reduce(lambda x, y: x * y, range(1, n + 1))

def factorial(n):
    "Iterate normally"
    res = 1
    for factor in range(1, n + 1):
        res *= factor
    return res
```

**`factorial_test.py`** (file)
```python
def factorial(n):
    "Iterate by recursion"
    if n == 0: return 1
    return n * factorial(n - 1)

if __name__ == '__main__':
    for x in range(100000):
        print(factorial(x))
```

This is a convenient solution, and it allows me to save several yank and yank-pop operations.

**Comment by Dewdrops** [comment] 2016-04-07 07:09
All right.    
I've push some code to the `cross-buffer` branch to implement exchange across buffers. Please try it out to see if it works as expected.

**Comment by PythonNut** [comment] 2016-04-07 15:13
@Dewdrops when I try to exchange across a buffer, I get the following error:

> save-excursion: Marker points into wrong buffer: #&lt;marker (moves after insertion) at 147 in exchange_buffer_test2&gt;

**Comment by Dewdrops** [comment] 2016-04-08 02:53
@PythonNut  I've pushed a new version to `cross-buffer` branch, please have a try.

Note that I've not merged this branch back yet. You can clone and checkout that branch and `eval-buffer` evil-exchange.el manually to test the new version.

**Comment by PythonNut** [comment] 2016-04-08 03:19
Ah, you know, I was just thinking about what I did, and I just realized that I forgot the `git checkout ...`. 

Anyway, sorry for the bother. Say I have:
```
this i|s a test
```
```
this w|as a test
```
And I try to exchange `is` and `was`, running `evil-exchange` on `is`, then `was` with <kbd>gxiw</kbd>, I get this:

```
this wasis a test
```
```
this  a test
```

So it appears that text is moving in one direction, but not the other.

**Comment by Dewdrops** [comment] 2016-04-08 03:34
@PythonNut 

The one-direction behaviour seems caused by a silly typo in the implementation. ╮(╯_╰)╭

It should be fixed in the last commit (I committed about one hour ago). You can update to the current version  to see if the bug is still there.

**Comment by PythonNut** [comment] 2016-04-08 03:45
@Dewdrops 

Thank you! Everything appears to be working perfectly now.

**Comment by Dewdrops** [comment] 2016-04-08 04:22
Thanks for suggesting and helping test this feature. 

I've merged it back to master and updated the document. Now let's hope there's no new bug reported..  ^_^

**Closed** 2016-04-08 04:22 UTC
